version: "3"

services:
  front:
    image: "node_front_fuel:latest"
    build: "./front"
    user: node
    environment:
      - NODE_ENV=development
    command: "npm start"
    volumes:
      - "./front:/home/node/app"
      - "/home/node/app/node_modules"
    working_dir: /home/node/app
    ports:
      - "8080:3000"
    depends_on:
      - server
  server:
    image: "node_api_fuel:latest"
    build: "./api"
    user: node
    environment:
      - NODE_ENV=development
    command: "npm run dev"
    volumes:
      - "./api:/home/node/app"
      - "/home/node/app/node_modules"
    working_dir: /home/node/app
    ports:
      - "3000:8080"
    networks:
      - internal
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=fuel
    volumes:
      - "mongodb_data:/data/db"
    ports:
      - 27017:27017
    networks:
      - internal
  nginx:
    image: nginx:1.15-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
  certbot:
    image: certbot/certbot
networks:
  internal:
volumes:
  mongodb_data:
    driver: local
