version: "3"

services:
  server:
    image: "node:10-alpine"
    user: node
    environment:
      - NODE_ENV=development
    command: "npm run dev"
    volumes:
      - "./api:/home/node/app"
    working_dir: /home/node/app
    ports:
      - "3000:8080"
    networks:
      - internal
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=fuel
    volumes:
      - "./api/db:/data/db"
    ports:
      - 27017:27017
    networks:
      - internal
networks:
  internal:
