name: Docker Image CI Front

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:

  build-front:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      working-directory: ./front
      run: docker build . --file Prod.Dockerfile --tag fuel-front:$(date +%s)

  build-api:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      working-directory: ./api
      run: docker build . --file Prod.Dockerfile --tag fuel-api:$(date +%s)

  build-cron:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      working-directory: ./cron
      run: docker build . --file Prod.Dockerfile --tag fuel-cron:$(date +%s)
